/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args) {
        String word = "Hello World!";

        HuffmanTree huffmanTree = new HuffmanTree(word);

        System.out.println("|---- Huffman Coding ----|");
        huffmanTree.printCodeTable();
        System.out.println();
        
        String compressed = huffmanTree.compress(word);
        String decompressed = huffmanTree.decompress(compressed);  

        System.out.println("Original: " + word);
        System.out.println("Compressed: " + compressed);
        System.out.println("Decompressed: " + decompressed);
    }
}
